#program to draw with Turtle 
import turtle 
t = turtle.Turtle()
scr = turtle.bgcolor("cyan")
t.begin_fill()
t.color("green") 
for i in range(4):
    t.forward(200)
    t.left(90)
t.end_fill()
c = ["blue", "pink", "red", "orange", "yellow"] 
k = 0
for i in range(100, 0, -20):
    t.color(c[k])
    k += 1
    t.begin_fill()
    t.circle(i)
    t.end_fill()
t.hideturtle()
turtle.done()

#making a hut 
# t = turtle.Turtle()
# t.color("brown")
# t.begin_fill() 
# t.forward(200) 
# t.left(120)
# t.forward(200)
# t.left(120)
# t.forward(200)
# t.left(30)
# t.forward(150)
# t.left(90)
# t.forward(200)
# t.left(90)
# t.forward(150)
# t.end_fill()
# turtle.done()

#making flag 
# t = turtle.Turtle() 
# t.left(90)
# t.forward(320)
# t.color("orange")
# t.begin_fill()
# t.right(90)
# t.forward(150)
# t.right(90) 
# t.forward(100)
# t.right(90)
# t.forward(150)
# t.end_fill()
# t.color("black", "white")
# t.begin_fill()
# t.left(90) 
# t.forward(90)
# t.left(90)
# t.forward(150)
# t.left(90)
# t.forward(90)
# t.end_fill()
# t.color("green")
# t.begin_fill()
# t.backward(150)
# t.left(90)
# t.forward(150)
# t.left(90)
# t.forward(50)
# t.end_fill()
# turtle.done()